{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.matrix",
    "module": "matrix-android-lib",
    "version": "2.0.8LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uvgjwxmkqnacjn44nn2mw5xryy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "matrix-android-lib-2.0.8LOCAL.aar",
          "url": "matrix-android-lib-2.0.8LOCAL.aar",
          "size": 334253,
          "sha512": "e9878b6509b87286f739334f7debc3b3d6542f3e9cf9830d2eeaa94d62a7addac912de02d6379643699c6404a800279a98c59659d41fe5aa365866e9524174e5",
          "sha256": "edd591339fc941509d73eed0e37e9921c1321fc7a72ce916b528ced161163d88",
          "sha1": "6850d32428d39b3143c3d017ae010cbf89b27016",
          "md5": "0f27d51348ba5450266c7bd083855a01"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "matrix-android-lib-2.0.8LOCAL.aar",
          "url": "matrix-android-lib-2.0.8LOCAL.aar",
          "size": 334253,
          "sha512": "e9878b6509b87286f739334f7debc3b3d6542f3e9cf9830d2eeaa94d62a7addac912de02d6379643699c6404a800279a98c59659d41fe5aa365866e9524174e5",
          "sha256": "edd591339fc941509d73eed0e37e9921c1321fc7a72ce916b528ced161163d88",
          "sha1": "6850d32428d39b3143c3d017ae010cbf89b27016",
          "md5": "0f27d51348ba5450266c7bd083855a01"
        }
      ]
    }
  ]
}
