{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.matrix",
    "module": "matrix-opengl-leak",
    "version": "2.0.8LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uvgjwxmkqnacjn44nn2mw5xryy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.matrix",
          "module": "matrix-android-lib",
          "version": {
            "requires": "2.0.8LOCAL"
          }
        },
        {
          "group": "com.tencent.matrix",
          "module": "matrix-android-commons",
          "version": {
            "requires": "2.0.8LOCAL"
          }
        },
        {
          "group": "com.tencent.matrix",
          "module": "matrix-backtrace",
          "version": {
            "requires": "2.0.8LOCAL"
          }
        }
      ],
      "files": [
        {
          "name": "matrix-opengl-leak-2.0.8LOCAL.aar",
          "url": "matrix-opengl-leak-2.0.8LOCAL.aar",
          "size": 604091,
          "sha512": "6e79694583c80c45bdf91e0e1b5b731e4b0156c5ea29dd3949325b6834d70ed8ad9942ec8cfbb46aa90e4994efad29e6e3b58762eef4edc2f3bc48f5a3449fc5",
          "sha256": "4b52283d00d8852fd89073466400418e5d9cd65915d86046c046a280efd40d2d",
          "sha1": "f17a7d7dfa9e342a81f5bd81fef0b7400c412a96",
          "md5": "ed6be76ad2c0cdb2b629d15358531dfb"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "matrix-opengl-leak-2.0.8LOCAL.aar",
          "url": "matrix-opengl-leak-2.0.8LOCAL.aar",
          "size": 604091,
          "sha512": "6e79694583c80c45bdf91e0e1b5b731e4b0156c5ea29dd3949325b6834d70ed8ad9942ec8cfbb46aa90e4994efad29e6e3b58762eef4edc2f3bc48f5a3449fc5",
          "sha256": "4b52283d00d8852fd89073466400418e5d9cd65915d86046c046a280efd40d2d",
          "sha1": "f17a7d7dfa9e342a81f5bd81fef0b7400c412a96",
          "md5": "ed6be76ad2c0cdb2b629d15358531dfb"
        }
      ]
    }
  ]
}
