{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.matrix",
    "module": "matrix-memory-canary",
    "version": "2.0.8LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uvgjwxmkqnacjn44nn2mw5xryy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.tencent.matrix",
          "module": "matrix-android-lib",
          "version": {
            "requires": "2.0.8LOCAL"
          }
        }
      ],
      "files": [
        {
          "name": "matrix-memory-canary-2.0.8LOCAL.aar",
          "url": "matrix-memory-canary-2.0.8LOCAL.aar",
          "size": 105360,
          "sha512": "a6c6971e8727ca731ad1910b6459689d6e4d9a8045cc9e1421901e59de1b78264895b902a622ebd1b691391a925cfae046ab34c491894fd9bce74895eb7b0d37",
          "sha256": "761b81dab6454c842edf309b813d3acf63d4dd17d66e6931f3c6e32969851736",
          "sha1": "07c7a1b4fff5fb7c98f8b45831da3b365c247b76",
          "md5": "49fc52738b3047a4b731cfe092808e87"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "matrix-memory-canary-2.0.8LOCAL.aar",
          "url": "matrix-memory-canary-2.0.8LOCAL.aar",
          "size": 105360,
          "sha512": "a6c6971e8727ca731ad1910b6459689d6e4d9a8045cc9e1421901e59de1b78264895b902a622ebd1b691391a925cfae046ab34c491894fd9bce74895eb7b0d37",
          "sha256": "761b81dab6454c842edf309b813d3acf63d4dd17d66e6931f3c6e32969851736",
          "sha1": "07c7a1b4fff5fb7c98f8b45831da3b365c247b76",
          "md5": "49fc52738b3047a4b731cfe092808e87"
        }
      ]
    }
  ]
}
